name: Serge CI

on:
  workflow_dispatch:

env:
  PAT: ${{ secrets.GH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set Git Configs & Secrets
        uses: rokibhasansagar/custom_workflows/git_config@main
      - name: SSH Keepalive
        uses: rokibhasansagar/custom_workflows/ssh_keepalive@main
      - name: Add ngrok Session
        run: |
          curl -sL https://gist.github.com/rokibhasansagar/077b66b16cd50e50e5ad9489084dc926/raw/ngrok2actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: eu
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO_PURPOSE: "Primary UserGE Runner"
      - name: Build and Run Userge
        timeout-minutes: 350
        continue-on-error: true
        run: |
          while ((${SECONDS_LEFT:=5} > 0)); do
            printf "Please wait %ss ...\n" "${SECONDS_LEFT}"
            sleep 1
            SECONDS_LEFT=$((${SECONDS_LEFT} - 1))
          done && unset SECONDS_LEFT
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin &>/dev/null
          echo "::group::Prepare Repos"
          git clone --filter blob:none ${{ secrets.USERGEREPO }} bot && cd bot
          curl -sL ${{ secrets.USERGIST_CONFIG }} -o config.env
          curl -sL ${{ secrets.USERGIST_COMPOSE }} -o docker-compose.yml
          echo "::endgroup::"
          echo "::group::Build Containers"
          docker-compose up -d
          echo "::endgroup::"
          sleep 5s
          echo "::group::Startup Containers"
          docker-compose logs -f &
          sleep 60s
          curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash 2>/dev/null
          echo "::endgroup::"
      - name: Trigger new workflow
        continue-on-error: true
        run: |
          curl -X POST --header "Authorization: token ${PAT}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"main"}'
