name: CI

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GitHubMail: "rokibhasansagar2014@outlook.com"
      GitHubName: "rokibhasansagar"

    steps:
      - name: Set Git Config & Token
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      # Checkout The Workflow, Shallow Clone
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.GH_TOKEN }}"
          fetch-depth: "1"
      - name: Cleanup
        uses: rokibhasansagar/slimhub_actions@main
      - name: Running Userge
        timeout-minutes: 340
        continue-on-error: true
        run: |
          echo "::group::Prepare Repos"
          git clone ${{ secrets.USERGEREPO }} bot && cd bot
          curl -sL ${{ secrets.USERGIST_CONFIG }} -o config.env
          curl -sL ${{ secrets.USERGIST_COMPOSE }} -o docker-compose.yml
          echo "::endgroup::"
          echo "::group::Build Containers"
          docker-compose up -d
          echo "::endgroup::"
          echo "::group::Startup Containers"
          docker-compose logs -f
          echo "::endgroup::"
      - name: Trigger new workflow
        run: |
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"main"}'
