name: Serge CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      GitHubMail: ${{ secrets.GitHubMail }}
      GitHubName: ${{ secrets.GitHubName }}

    steps:
      - name: Set Git Config & Token
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global credential.helper store
          echo "https://${GitHubName}:${{ secrets.GH_TOKEN }}@github.com" > ~/.git-credentials
      - uses: actions/checkout@main
        with:
          token: "${{ secrets.GH_TOKEN }}"
          fetch-depth: "1"
      - name: Add ngrok Session
        run: |
          curl -sL https://gist.github.com/rokibhasansagar/077b66b16cd50e50e5ad9489084dc926/raw/ssh_keepalive.sh | bash
          curl -sL https://gist.github.com/rokibhasansagar/077b66b16cd50e50e5ad9489084dc926/raw/ngrok2actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          NGROK_REGION: eu
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          REPO_PURPOSE: "Primary UserGE Runner"
      - name: Build and Run Userge
        timeout-minutes: 340
        continue-on-error: true
        run: |
          while ((${SECONDS_LEFT:=5} > 0)); do
            printf "Please wait %ss ...\n" "${SECONDS_LEFT}"
            sleep 1
            SECONDS_LEFT=$((${SECONDS_LEFT} - 1))
          done && unset SECONDS_LEFT
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin &>/dev/null
          echo "::group::Prepare Repos"
          git clone ${{ secrets.USERGEREPO }} bot && cd bot
          curl -sL ${{ secrets.USERGIST_CONFIG }} -o config.env
          curl -sL ${{ secrets.USERGIST_COMPOSE }} -o docker-compose.yml
          echo "::endgroup::"
          echo "::group::Build Containers"
          docker-compose up -d
          echo "::endgroup::"
          echo "::group::Startup Containers"
          curl -sL https://github.com/rokibhasansagar/slimhub_actions/raw/main/cleanup.sh | bash &>/dev/null & disown;
          docker-compose logs -f
          echo "::endgroup::"
      - name: Trigger new workflow
        continue-on-error: true
        run: |
          curl -X POST --header "Authorization: token ${{ secrets.GH_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/main.yml/dispatches -d '{"ref":"main"}'
